<a href="https://colab.research.google.com/github/lazizrakhmat/DS-Numpy/blob/main/2_1_5_Arr_Or_Pr_4Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. 
## 2.1. NumPy kutubxonasi bilan ishlash

In [1]:
import numpy as np

### 2.1.3. Massivga yo'naltirilgan dasturlash

### Tartiblash (`Sorting`)

In [18]:
# data
arr = np.random.rand(4) # ta taxminiy elementlardan tashkil topgan massiv
arr

array([0.31169484, 0.60677123, 0.71700788, 0.69256857])

## ```sort```funksiyasi

In [21]:
sorted_arr = np.sort(arr) # arr massivning tartiblangan versiyasi
sorted_arr

array([0.31169484, 0.60677123, 0.69256857, 0.71700788])

In [23]:
# 2 usul
arr.sort() # arr -ning tartiblangan ko'rinishi
arr

array([0.31169484, 0.60677123, 0.69256857, 0.71700788])

In [26]:
# teskari tartiblash]
rev_arr = -np.sort(-arr) # teskari tartibdagi arr
rev_arr

array([0.71700788, 0.69256857, 0.60677123, 0.31169484])

In [27]:
# 2 D array (massiv)
arr2d = np.random.rand(2, 4) # (2, 4) random massiv
arr2d

array([[0.53918399, 0.50469323, 0.1082719 , 0.44984392],
       [0.33435207, 0.45803609, 0.99578917, 0.56074576]])

In [29]:
# axis = 0 --> Qator
row_srt = np.sort(arr2d, axis=0) # arr2d xar bir qator bo'yicha tartiblangan ko'rinishi
row_srt

array([[0.33435207, 0.45803609, 0.1082719 , 0.44984392],
       [0.53918399, 0.50469323, 0.99578917, 0.56074576]])

In [30]:
# axis = 1 --> Ustun
col_srt = np.sort(arr2d, axis=1) # arr2d xar bir ustun bo'yicha tartiblangan
col_srt

array([[0.1082719 , 0.44984392, 0.50469323, 0.53918399],
       [0.33435207, 0.45803609, 0.56074576, 0.99578917]])