<a href="https://colab.research.google.com/github/lazizrakhmat/DS-Numpy/blob/main/2_1_3_Arr_Or_Pr_1_Logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. 
## 2.1. NumPy kutubxonasi bilan ishlash

In [2]:
import numpy as np

### 2.1.3. Massivga yo'naltirilgan dasturlash

### Shart operatori sifatida `where` dan foydalanish

### Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: `xarr` va `yarr`. Agarda shart `True`ni qanoatlantirsa `xarr` elementini qabul qilgan aksincha esa `yarr` elementini qabul qilgan yangi massiv hosil qilinsin.

In [4]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [5]:
# Shart
cond = np.array([True, False, True, True, False])


In [6]:
# where
result = np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [8]:
arr = np.random.rand(4, 4) # 4 ga 4 o'lchamli taxminiy elementlar, massiv
arr

array([[0.63266279, 0.83709457, 0.5703425 , 0.16839113],
       [0.67245949, 0.83536189, 0.65077167, 0.69235085],
       [0.46233924, 0.33039661, 0.91484058, 0.7858841 ],
       [0.54424383, 0.10408241, 0.81929967, 0.67444948]])

In [9]:
# where 
results = np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarini es 2 ga almashtirish
results

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])