<a href="https://colab.research.google.com/github/lazizrakhmat/DS-Numpy/blob/main/2_1_3_Arr_Or_Pr_1_Logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. 
## 2.1. NumPy kutubxonasi bilan ishlash

In [1]:
import numpy as np

### 2.1.3. Massivga yo'naltirilgan dasturlash

### Shart operatori sifatida `where` dan foydalanish

### Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: `xarr` va `yarr`. Agarda shart `True`ni qanoatlantirsa `xarr` elementini qabul qilgan aksincha esa `yarr` elementini qabul qilgan yangi massiv hosil qilinsin.

In [ ]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [ ]:
# Shart
cond = np.array([True, False, True, True, False])


In [ ]:
# where
result = np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr = np.random.rand(4, 4) # 4 ga 4 o'lchamli taxminiy elementlar, massiv
arr

array([[0.63266279, 0.83709457, 0.5703425 , 0.16839113],
       [0.67245949, 0.83536189, 0.65077167, 0.69235085],
       [0.46233924, 0.33039661, 0.91484058, 0.7858841 ],
       [0.54424383, 0.10408241, 0.81929967, 0.67444948]])

In [ ]:
# where 
results = np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarini es 2 ga almashtirish
results

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Arifmetik amallar

Kopaytirish, bo'lish, qo'shish, ayirish va h.k amallar

In [2]:
#data 
arr1 = np.arange(6).reshape(2, 3) # 0~6 gacha elementlardan tashkil topgan array
arr2 = np.arange(6, 12).reshape(2, 3) # 6~11 gacha bo'lgan elementlardan tashkil topgan array
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
# Ko'paytirish
arr1 * arr2 # arr1 ning elementlarini arr2 elementlariga ko'paytirib beradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [5]:
# Bo'lish 
arr2/arr1 # arr1 ning elementlarini arr2 ning mos elementlariga bo'lib beradi

<ipython-input-5-3cd8b7fd3075>:2: RuntimeWarning: divide by zero encountered in true_divide
  arr2/arr1 # arr1 ning elementlarini arr2 ning mos elementlariga bo'lib beradi


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [6]:
# Qo'shish
arr1 + arr2 

array([[ 6,  8, 10],
       [12, 14, 16]])

In [7]:
# Ayirish
arr2 - arr1 # arr2 ning arr1 ning mos elementlaridan ayirish

array([[6, 6, 6],
       [6, 6, 6]])

In [8]:
# Kvadrat oshsirish (square)
arr2**2 

array([[ 36,  49,  64],
       [ 81, 100, 121]])

In [9]:
# Kvadrat ildizdan (sqrt)
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])