<a href="https://colab.research.google.com/github/rakhmatAI/DataScience_numpy/blob/main/_1_Creating_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data1 = [3.2, 4, 2, 6] # list
arr1 = np.array(data1) # array


In [3]:
data1

[3.2, 4, 2, 6]

In [4]:
arr1

array([3.2, 4. , 2. , 6. ])

In [5]:
data2 = (4, 5, 1.4, 3, 7) # tuple
arr2 = np.array(data2)

In [6]:
arr2

array([4. , 5. , 1.4, 3. , 7. ])

In [8]:
arr1.ndim # array1 ning o'lchami

1

In [9]:
arr2.ndim # array2 ning o'lchami

1

In [11]:
data3 = [[1, 4, 2], [5, 6, 3]] # nested list 2 o'lchamli
arr3 = np.array(data3) # array3

In [12]:
arr3.ndim

2

In [15]:
data4 = [[[2, 4, 6], [1, 3, 5], [7.5, 8, 9]]] # nested list 3 o'lchamli
arr4 = np.array(data4) # array4

In [16]:
arr4.ndim

3

In [17]:
# .shape --> qator va ustunlar sonini ko'rsatib beradi (q, u) 
# .size  --> elementlar sonini ko'rsatadi

In [21]:
arr3.shape

(2, 3)

In [24]:
arr3.size

6

N-o'lchamli massivlarni yaratishda boshqa usullari 

```zeros``` va ``` ones```
funksiyalari yordamida massivlar yaratish




In [28]:
arr5 = np.zeros((2, 4)) # barcha elementlari 0 ga teng (2, 4)
arr5 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
arr6 = np.ones((3, 2)) # barcha elementlari 1 ga teng (3, 2)
arr6

array([[1., 1.],
       [1., 1.],
       [1., 1.]])



```arange``` funksiyasi yordamida



In [31]:
arr7 = np.arange(4, 20, 2) # 4 dan 20 gacha bo'lgan qiymatlarni 2 qadam bilan massivga joylab beradi
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
arr7 = np.arange(20) # 0 dan 20 gacha bo'lgan 1 qadamlarni massivga joylab beradi
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])