<a href="https://colab.research.google.com/github/rakhmatAI/DataScience_numpy/blob/main/_4_Boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. 
## 2.1. NumPy kutubxonasi bilan ishlash

In [1]:
import numpy as np

In [3]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [5]:
# data
data = np.random.rand(7, 4)
data

array([[0.78954264, 0.92463015, 0.73821613, 0.97255602],
       [0.72600676, 0.58212415, 0.06668968, 0.88516983],
       [0.12576639, 0.91849839, 0.02873008, 0.41883383],
       [0.50445763, 0.15642633, 0.72562352, 0.9226235 ],
       [0.86281267, 0.08762724, 0.4510818 , 0.72738057],
       [0.73487126, 0.77848678, 0.38018525, 0.11401359],
       [0.60869199, 0.722904  , 0.8482773 , 0.25323092]])

In [6]:
names == 'Hasan'


array([ True, False, False, False,  True, False, False])

In [7]:
data[names == 'Hasan'] # Hasanga tegishli barcha ma'lumotlarni ajratib olish

array([[0.78954264, 0.92463015, 0.73821613, 0.97255602],
       [0.86281267, 0.08762724, 0.4510818 , 0.72738057]])

In [8]:
data[names == 'Elyor'] # Elyorga tegishli barcha ma'lumotlarni ajratib olish

array([[0.50445763, 0.15642633, 0.72562352, 0.9226235 ],
       [0.60869199, 0.722904  , 0.8482773 , 0.25323092]])

In [9]:
data[names == 'Hasan', 2:] # H tegishli oxirgi ikkita ustundagi ma'lumotlarni ajratib olish

array([[0.73821613, 0.97255602],
       [0.4510818 , 0.72738057]])

In [11]:
data[names != 'Hasan'] # (!=) H dan tashqari barcha insonlarning ma'lumotlarini olish

array([[0.72600676, 0.58212415, 0.06668968, 0.88516983],
       [0.12576639, 0.91849839, 0.02873008, 0.41883383],
       [0.50445763, 0.15642633, 0.72562352, 0.9226235 ],
       [0.73487126, 0.77848678, 0.38018525, 0.11401359],
       [0.60869199, 0.722904  , 0.8482773 , 0.25323092]])

In [12]:
data[~(names == 'Hasan')] # (~)

array([[0.72600676, 0.58212415, 0.06668968, 0.88516983],
       [0.12576639, 0.91849839, 0.02873008, 0.41883383],
       [0.50445763, 0.15642633, 0.72562352, 0.9226235 ],
       [0.73487126, 0.77848678, 0.38018525, 0.11401359],
       [0.60869199, 0.722904  , 0.8482773 , 0.25323092]])

In [13]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[0.78954264 0.92463015 0.73821613 0.97255602]
 [0.72600676 0.58212415 0.06668968 0.88516983]
 [0.12576639 0.91849839 0.02873008 0.41883383]
 [0.50445763 0.15642633 0.72562352 0.9226235 ]
 [0.86281267 0.08762724 0.4510818  0.72738057]
 [0.73487126 0.77848678 0.38018525 0.11401359]
 [0.60869199 0.722904   0.8482773  0.25323092]]


In [15]:
mask = (names == 'Hasan') | (names == 'Husan') # "|" or (yoki)
mask 

array([ True,  True, False, False,  True, False, False])

In [16]:
data[mask] # Hasan va Husanga tegishli ma'lumotlarni ajratib olish

array([[0.78954264, 0.92463015, 0.73821613, 0.97255602],
       [0.72600676, 0.58212415, 0.06668968, 0.88516983],
       [0.86281267, 0.08762724, 0.4510818 , 0.72738057]])

In [17]:
data

array([[0.78954264, 0.92463015, 0.73821613, 0.97255602],
       [0.72600676, 0.58212415, 0.06668968, 0.88516983],
       [0.12576639, 0.91849839, 0.02873008, 0.41883383],
       [0.50445763, 0.15642633, 0.72562352, 0.9226235 ],
       [0.86281267, 0.08762724, 0.4510818 , 0.72738057],
       [0.73487126, 0.77848678, 0.38018525, 0.11401359],
       [0.60869199, 0.722904  , 0.8482773 , 0.25323092]])

In [20]:
data[data<0]=0
data

array([[0.78954264, 0.92463015, 0.73821613, 0.97255602],
       [0.72600676, 0.58212415, 0.06668968, 0.88516983],
       [0.12576639, 0.91849839, 0.02873008, 0.41883383],
       [0.50445763, 0.15642633, 0.72562352, 0.9226235 ],
       [0.86281267, 0.08762724, 0.4510818 , 0.72738057],
       [0.73487126, 0.77848678, 0.38018525, 0.11401359],
       [0.60869199, 0.722904  , 0.8482773 , 0.25323092]])