<a href="https://colab.research.google.com/github/lazizrakhmat/DS-Numpy/blob/main/linearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Numpy kutubxonasi.
### Chiziqli algebra


In [24]:
import numpy as np 

In [25]:
# Linear Algebra
from numpy.linalg import inv

In [3]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [4]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
y = np.array([[5., 5., 6.],[1., 4., 6.]])

In [8]:
y

array([[5., 5., 6.],
       [1., 4., 6.]])

In [9]:
x+y

array([[ 6.,  7.,  9.],
       [ 5.,  9., 12.]])

In [10]:
x-y

array([[-4., -3., -3.],
       [ 3.,  1.,  0.]])

In [11]:
x*2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [12]:
x = np.array([[1., 2., 3.],[4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
y = np.array([[7., 6.],[9., 5.], [8., 5.]])
y

array([[7., 6.],
       [9., 5.],
       [8., 5.]])

In [19]:
x.dot(y) # x*y


array([[ 49.,  31.],
       [121.,  79.]])

In [20]:
np.dot(x, y) # x*y

array([[ 49.,  31.],
       [121.,  79.]])

In [21]:
y.dot(x) # y*x

array([[31., 44., 57.],
       [29., 43., 57.],
       [28., 41., 54.]])

In [22]:
np.dot(y, x) # y*x 

array([[31., 44., 57.],
       [29., 43., 57.],
       [28., 41., 54.]])