<a href="https://colab.research.google.com/github/lazizrakhmat/DS-Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Numpy kutubxonasi.
### Fayllar bilan ishlash


In [1]:
import numpy as np 

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('data', arr) # save() np ko'rinishidagi array'larni saqlaydi
arr2 = np.load('data.npy')

In [5]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr1 = np.arange(20)

In [7]:
np.savez('arrays', a=arr1, b=arr2) # savez() bir va undan ko'p bo'lgan array'larni saqlaydi

In [8]:
arrays = np.load('arrays.npz') # load() - saqlangan np.array' filelarni ochadi

In [9]:
arrays['a']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
arrays['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.savez_compressed('array_comp.npz', a=arr, b=arr1) # savez_compressed() - bu birnechta katta hajmdagi arraylarni compress qilib saqlaydi

In [12]:
arrays_comp = np.load('array_comp.npz')

In [14]:
arrays_comp['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arrays_comp['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])